version: '3.8'

services:
  discord-bot:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: discord-confession-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - NODE_ENV=production
      - TZ=Asia/Kuala_Lumpur
    volumes:
      # FIX: Use the simple bind mount syntax for host path persistence.
      # This tells Docker explicitly to create a bind mount from the host path.
      - /opt/discord-bot/data:/app/data
      
      # FIX: Use the simple bind mount syntax for logs directory.
      - /opt/discord-bot/logs:/app/logs
      
    networks:
      - discord-bot-network
      
    # Resource limits for Raspberry Pi (Deploy section is for Swarm mode, but fine for local testing)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
          
    # Health check to monitor bot status
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed'); process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Labels for better organization in Portainer
    labels:
      - "traefik.enable=false"
      - "com.docker.compose.project=discord-bot"
      - "description=Discord Anonymous Confession Bot"

# --- REMOVED VOLUME DEFINITIONS ---
# Removed the complex 'driver_opts' definitions as they were forcing bind mounts
# which failed when the host path was missing. The simple syntax in services
# handles this creation more gracefully.

networks:
  discord-bot-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16